# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
 adapter: postgresql
 encoding: utf8
 database: blog_app_development
 pool: 5

test: &test
 adapter: postgresql
 encoding: utf8
 database: blog_app_test
 pool: 5

production:
 adapter: postgresql
 encoding: utf8
 database: blog_app_production
 pool: 5
